# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=100; python3 -u safe_behavior.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --beta 0.2

# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=100; python3 -u safe_critic.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --beta 0.2

# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=1; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed${seed}/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed${seed}/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000

# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=1; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000
# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=100; python3 -u safe_critic.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --beta 0.2
# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=100; python3 -u safe_behavior.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --beta 0.2


# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=0; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=1; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=2; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=3; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=4; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512




# "OfflineAntVelocityGymnasium-v1"
# r:0.694, c: 0.495
# TASK="OfflineAntVelocityGymnasium-v1"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 6e-4 --v_lr 6e-4
# r:0.886, c: 1.287
# TASK="OfflineAntVelocityGymnasium-v1"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4
# r:0.880, c: 0.891
# TASK="OfflineAntVelocityGymnasium-v1"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 3e-4 --q_lr 3e-4 --v_lr 3e-4
# TASK="OfflineAntVelocityGymnasium-v1"; seed=0; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 3e-4 --q_lr 3e-4 --v_lr 3e-4
# TASK="OfflineAntVelocityGymnasium-v1"; seed=1; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 3e-4 --q_lr 3e-4 --v_lr 3e-4
# TASK="OfflineAntVelocityGymnasium-v1"; seed=2; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 3e-4 --q_lr 3e-4 --v_lr 3e-4
# TASK="OfflineAntVelocityGymnasium-v1"; seed=3; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 3e-4 --q_lr 3e-4 --v_lr 3e-4
# TASK="OfflineAntVelocityGymnasium-v1"; seed=4; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 3e-4 --q_lr 3e-4 --v_lr 3e-4

# OfflineHalfCheetahVelocityGymnasium
# r: 0.857, c: 0.0
# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 6e-4 --v_lr 6e-4

# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 20 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 6e-4 --v_lr 6e-4

# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 30 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 6e-4 --v_lr 6e-4

# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 40 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 6e-4 --v_lr 6e-4

# TASK="OfflineHalfCheetahVelocityGymnasium-v1"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 50 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 6e-4 --v_lr 6e-4


# OfflineHopperVelocityGymnasium-v1
# TASK="OfflineHopperVelocityGymnasium-v1"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 3e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000

# OfflineSwimmerVelocityGymnasium-v1
# TASK="OfflineSwimmerVelocityGymnasium-v1"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt170.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000

# OfflineWalker2dVelocityGymnasium-v1
# TASK="OfflineWalker2dVelocityGymnasium-v1"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 5e-5 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 50 --train_epochs 8000

# OfflineCarRun-v0 r:1.089/0.975, c: 0.98
# TASK="OfflineCarRun-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 30 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 

# TASK="OfflineCarRun-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.7 --cost_limit 1.0 --cost_scale 30 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 

# TASK="OfflineCarRun-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.3 --cost_limit 1.0 --cost_scale 30 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 

# TASK="OfflineCarRun-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.1 --cost_limit 1.0 --cost_scale 30 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 
# TASK="OfflineCarRun-v0"; seed=0; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.1 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 
# TASK="OfflineCarRun-v0"; seed=1; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.1 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 
# TASK="OfflineCarRun-v0"; seed=2; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.1 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 
# TASK="OfflineCarRun-v0"; seed=3; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.1 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 
# TASK="OfflineCarRun-v0"; seed=4; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.1 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 
# OfflineAntRun-v0 r:0.0, c: 0.0
# TASK="OfflineAntRun-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000

# OfflineAntCircle-v0 r:0.0, c: 0.0
# TASK="OfflineAntCircle-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000

# OfflineBallCircle-v0 r:0.0, c: 0.0
# TASK="OfflineBallCircle-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 
# TASK="OfflineBallCircle-v0"; seed=0; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 
# TASK="OfflineBallCircle-v0"; seed=1; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 
# TASK="OfflineBallCircle-v0"; seed=2; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 
# TASK="OfflineBallCircle-v0"; seed=3; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 
# TASK="OfflineBallCircle-v0"; seed=4; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 

# OfflineCarCircle-v0 r:0.0, c: 0.0
# TASK="OfflineCarCircle-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True 
# TASK="OfflineCarCircle-v0"; seed=0; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflineCarCircle-v0"; seed=1; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflineCarCircle-v0"; seed=2; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflineCarCircle-v0"; seed=3; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflineCarCircle-v0"; seed=4; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512


# OfflineCarButton1Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflineCarButton1Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 

# OfflineCarButton2Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflineCarButton2Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 

# OfflineCarCircle1Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflineCarCircle1Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 

# OfflineCarCircle2Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflineCarCircle2Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 

# OfflineCarGoal1Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflineCarGoal1Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --policy_batchsize 512
# TASK="OfflineCarGoal1Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 20 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --policy_batchsize 512
# TASK="OfflineCarGoal1Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 30 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --policy_batchsize 512

# OfflineCarGoal2Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflineCarGoal2Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
# TASK="OfflineCarGoal2Gymnasium-v0"; seed=0; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
# TASK="OfflineCarGoal2Gymnasium-v0"; seed=1; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
# TASK="OfflineCarGoal2Gymnasium-v0"; seed=2; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
# TASK="OfflineCarGoal2Gymnasium-v0"; seed=3; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
# TASK="OfflineCarGoal2Gymnasium-v0"; seed=4; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
# OfflineCarPush1Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflineCarPush1Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True

# OfflineCarPush2Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflineCarPush2Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 4000 --pid True --use_lagrangian True

# safety_gymnasium: point
# "OfflinePointButton1Gymnasium-v0",         # 8
# "OfflinePointButton2Gymnasium-v0",         # 9
# "OfflinePointCircle1Gymnasium-v0",         # 10
# "OfflinePointCircle2Gymnasium-v0",         # 11
# "OfflinePointGoal1Gymnasium-v0",           # 12
# "OfflinePointGoal2Gymnasium-v0",           # 13
# "OfflinePointPush1Gymnasium-v0",           # 14
# "OfflinePointPush2Gymnasium-v0",           # 15

# OfflinePointButton1Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflinePointButton1Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
TASK="OfflinePointButton1Gymnasium-v0"; seed=0; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
TASK="OfflinePointButton1Gymnasium-v0"; seed=1; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
TASK="OfflinePointButton1Gymnasium-v0"; seed=2; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
TASK="OfflinePointButton1Gymnasium-v0"; seed=3; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
TASK="OfflinePointButton1Gymnasium-v0"; seed=4; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
# OfflinePointButton2Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflinePointButton2Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512

# OfflinePointCircle1Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflinePointCircle1Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflinePointCircle1Gymnasium-v0"; seed=0; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflinePointCircle1Gymnasium-v0"; seed=1; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflinePointCircle1Gymnasium-v0"; seed=2; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflinePointCircle1Gymnasium-v0"; seed=3; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflinePointCircle1Gymnasium-v0"; seed=4; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# OfflinePointCircle2Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflinePointCircle2Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512

# OfflinePointGoal1Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflinePointGoal1Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflinePointGoal1Gymnasium-v0"; seed=0; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflinePointGoal1Gymnasium-v0"; seed=1; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflinePointGoal1Gymnasium-v0"; seed=2; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflinePointGoal1Gymnasium-v0"; seed=3; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflinePointGoal1Gymnasium-v0"; seed=4; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# OfflinePointGoal2Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflinePointGoal2Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512

# OfflinePointPush1Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflinePointPush1Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512

# OfflinePointPush2Gymnasium-v0 r:0.0, c: 0.0
# TASK="OfflinePointPush2Gymnasium-v0"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-4 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512

# PointRobot
# TASK="PointRobot"; seed=100; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512