# TASK="OfflinePointGoal2Gymnasium-v0"; seed=0; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflinePointGoal2Gymnasium-v0"; seed=1; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflinePointGoal2Gymnasium-v0"; seed=2; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflinePointGoal2Gymnasium-v0"; seed=3; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
# TASK="OfflinePointGoal2Gymnasium-v0"; seed=4; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512

# TASK="OfflinePointButton1Gymnasium-v0"; seed=0; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
# TASK="OfflinePointButton1Gymnasium-v0"; seed=1; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
# TASK="OfflinePointButton1Gymnasium-v0"; seed=2; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
# TASK="OfflinePointButton1Gymnasium-v0"; seed=3; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512
# TASK="OfflinePointButton1Gymnasium-v0"; seed=4; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 --policy_batchsize 512

# TASK="OfflineWalker2dVelocityGymnasium-v1"; seed=0; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 5e-5 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 50 --train_epochs 8000
# TASK="OfflineWalker2dVelocityGymnasium-v1"; seed=1; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 5e-5 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 50 --train_epochs 8000
# TASK="OfflineWalker2dVelocityGymnasium-v1"; seed=2; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 5e-5 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 50 --train_epochs 8000
# TASK="OfflineWalker2dVelocityGymnasium-v1"; seed=3; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 5e-5 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 50 --train_epochs 8000
# TASK="OfflineWalker2dVelocityGymnasium-v1"; seed=4; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 5e-5 --q_lr 3e-4 --v_lr 3e-4 --pretrain_epochs 50 --train_epochs 8000

TASK="OfflinePointButton2Gymnasium-v0"; seed=0; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
TASK="OfflinePointButton2Gymnasium-v0"; seed=1; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
TASK="OfflinePointButton2Gymnasium-v0"; seed=2; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
TASK="OfflinePointButton2Gymnasium-v0"; seed=3; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
TASK="OfflinePointButton2Gymnasium-v0"; seed=4; python3 -u safe_policy.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed} --actor_load_path ./Safe_model_factory/${TASK}-baseline-seed100/behavior_ckpt200.pth --critic_load_path ./Safe_model_factory/${TASK}-baseline-seed100/ --beta 0.01 --mode online --slack_bound 0.5 --cost_limit 1.0 --cost_scale 10 --n_policy_epochs 1000 --policy_lr 1e-5 --q_lr 1e-4 --v_lr 1e-4 --pretrain_epochs 100 --train_epochs 2000 -policy_batchsize 512
